name: env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - spot
  - numpy
  - matplotlib 
  - pydot 
  - networkx 
  - pygraphviz 
  - pytest
  - scipy 
  - lark
  - sortedcontainers
  - tqdm 
  - pip
  - pip:
    - dd
    
